language: python
python: "3.6"
before_install: 
 - openssl aes-256-cbc -k $DEPLOY_KEY -md sha256 -in langresource-deploy.enc -out langresource-deploy -d
 - eval `ssh-agent -s`
 - chmod 0600 langresource-deploy
 - ssh-add langresource-deploy
 - rm langresource-deploy
 - git config --global user.name "Telegram-zhCN-bot"
 - git config --global user.email "zhcn@daze.moe"
install: "pip install beautifulsoup4 requests"
script: 
 - python source-update.py
 - python translate-update.py
 - git status
 - git add source/*
 - git add zh-CN/*
 - git commit -m "Update Languages"
 - git push git@github.com:telegram-zhCN/telegram-language-resources.git HEAD:master

