language: python
python: "3.6"
before_install:
 - openssl aes-256-cbc -k $DEPLOY_KEY -md sha256 -in langresource-deploy.enc -out langresource-deploy -d
 - eval `ssh-agent -s`
 - chmod 0600 langresource-deploy
 - ssh-add langresource-deploy
 - rm langresource-deploy
 - git config --global user.name "Telegram-zhCN-bot"
 - git config --global user.email "zhcn@daze.moe"
install: "pip install beautifulsoup4 requests"
script:
 - git pull
 - python source-update.py
 - sed -i -E 's/^\/\/(\ |)(.*)$/\/\*\ \2\ \*\//gm' source/lang-desktop.strings
 - sed -i -E 's/^\/\/$//gm' source/Localizable-macOS.strings
 - sed -i -E 's/^\/\/(.*)$/\/\*\ \1\ \*\//gm' source/Localizable-macOS.strings
 - python translate-update.py
 - git status
 - git add source/*
 - git add zh-CN/*
 - git status
 - git diff --cached
 - git commit -m "Update Languages"
 - git push git@github.com:telegram-zhCN/telegram-language-resources.git HEAD:master
